logLevel: debug
tick: 10  # seconds
apiPort: 10250
metricsPort: 10255
cluster:
  nodes:
  - namespace: default
    name: node-0
    capacity:
      cpu: 4
      memory: 8Gi
      nvidia.com/gpu: 1
      pods: 2
    labels:
      beta.kubernetes.io/os: simulated
    taints:
      - key: kubernetes-simulator.io/kubelet
        value: simulator
        effect: NoSchedule
  - namespace: default
    name: node-1
    capacity:
      cpu: 8
      memory: 16Gi
      nvidia.com/gpu: 2
      pods: 4
    labels:
      beta.kubernetes.io/os: simulated
    taints:
      - key: kubernetes-simulator.io/kubelet
        value: simulator
        effect: NoSchedule
