# Optional (Default: info)
logLevel: debug

# Interval seconds for scheduling and updating the cluster.
# Optional (Default: 10)
tick: 10  

# apiPort: 10250
# metricsPort: 10255

# Start time at which the simulation starts in RFC3339 format.
# Optional (Default: now)
startClock: 2018-12-19T11:57:11+09:00 

cluster:
  nodes:
  - namespace: default
    name: node-0
    capacity:
      cpu: 4
      memory: 8Gi
      nvidia.com/gpu: 1
      pods: 2
    labels:
      beta.kubernetes.io/os: simulated
    taints:
      - key: kubernetes-simulator.io/kubelet
        value: simulator
        effect: NoSchedule
  - namespace: default
    name: node-1
    capacity:
      cpu: 8
      memory: 16Gi
      nvidia.com/gpu: 2
      pods: 4
    labels:
      beta.kubernetes.io/os: simulated
    taints:
      - key: kubernetes-simulator.io/kubelet
        value: simulator
        effect: NoSchedule