cluster:
  nodes:
  - name: node-0
    capacity:
      cpu: 4
      memory: 8Gi
      gpu: 1
      pods: 2
    operatingSystem: simulated
  - name: node-1
    capacity:
      cpu: 8
      memory: 16Gi
      gpu: 2
      pods: 4
    operatingSystem: simulated
taint:
  key:    kubernetes-scheduler-simulator.io/kubelet
  value:  simulator
  effect: NoSchedule
apiPort: 10250
metricsPort: 10255
logLevel: debug
